server:
  port: 9090
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    #    确认消息到交换机
    publisher-confirm-type: correlated
    #确认消息已经发送到队列
    publisher-returns: true
